### ISSUE TITLE
2 IA 2 couleurs

### ISSUE THREAD

**Issue by Khornya** [Khornya/dames-chinoises#2]
la partie ne finit jamais
![capture du 2018-04-13 13-20-52](https://user-images.githubusercontent.com/33462756/38732176-91ddd45c-3f1d-11e8-8949-c2e19cbb0c40.png)

**Comment by zaiterassia** [comment]
Le problème vient particulièrement du poid accordé au pion pour ne pas s'éloigner de la ligne droite entre le home et l'opposé, une fois devant le triangle opposé l'IA manque son coup pour partir vers la case vide et essaye de rester sur la ligne droite:
le problème est réglé en accordant -5 au poid;
